---
- name: Deploy docker image
  hosts: all
  become: yes
  vars:
    REGISTRY: "{{ lookup('ansible.builtin.env', 'REGISTRY') }}"
    SECRET_KEY: "{{ lookup('ansible.builtin.env', 'SECRET_KEY') }}"
    IMAGE_NAME: "{{ lookup('ansible.builtin.env', 'IMAGE_NAME') }}"
    TAG: "{{ lookup('ansible.builtin.env', 'TAG') }}"
    FULL_IMAGE_NAME: "{{ REGISTRY }}/{{ IMAGE_NAME }}:{{ TAG }}"

  tasks:
    - name: Login to docker registry
      community.docker.docker_login:
        registry: "{{ REGISTRY }}"
        password: "{{ SECRET_KEY }}"
        username: "nologin"
        state: present

    - name: Remove docker container
      command: docker container stop "{{ IMAGE_NAME }}"
      ignore_errors: true

    - name: Run dokcer container
      command: docker run -it -d --rm -p 8080:8080 --name "{{ IMAGE_NAME }}" "{{ FULL_IMAGE_NAME }}"
    # - name: Remove running container
    #   community.docker.docker_container:
    #     name: "{{ IMAGE_NAME }}"
    #     state: absent

    # - name: Run docker container
    #   community.docker.docker_container:  
    #     image: "{{ FULL_IMAGE_NAME }}"
    #     name: "{{ IMAGE_NAME }}"
    #     state: present
    #     recreate: yes
    #     cleanup: yes
    #     pull: true
    #     exposed_ports:
    #       - 8080
    #     ports:
    #       - "0.0.0.0:8080:8080"
    #     restart_policy: always
      
